Hw04 auth
Julija100/nodejs-homework-rest-api pull request #3
Opened 2021-11-24 16:15 UTC by Julija100

2021-11-24 21:20 UTC, KirillKulakow commented on utils/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
тут будет ошибка приложения - если сделать запрос на список контактов без авторизации

2021-11-24 21:22 UTC, KirillKulakow commented on utils/authenticate.js
> +    let user
здесь какой то непонятный код идет
сначала просто делаешь запрос на юзера по ид
если юзера нет - ошибка авторизации
если ок записать в req
вот и все

2021-11-24 21:23 UTC, KirillKulakow requested changes
need fix

2021-11-24 21:28 UTC, Julija100 commented on utils/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
Не будет.  try / catch делает свое дело.

2021-11-24 21:35 UTC, Julija100 commented on utils/authenticate.js
> +    let user
Этот вариант не хуже, позволяет отозвать токен отдельному юзеру в случае чего.

2021-11-26 20:22 UTC, KirillKulakow commented on utils/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
Ок, но лучше такое избегать, а то в ошибку что нибудь может совсем неожиданно уйти
+  если у тебя сломается соединение с сервером - ты этого не поймешь, так как возвращаться будет 401 ошибка - что не корректно

2021-11-26 20:29 UTC, KirillKulakow commented on utils/authenticate.js
> +    let user
Ок, буду по порядку
зачем делать проверки? 
`bearer === 'Bearer' && token` если ты уже и так токен перед этим проверифицировала (если была бы ошибка при верификации - уходит в catch)
`user.token === token` как можно сделать так чтобы токен найденного юзера не совпадал с входящим токеном - я не могу найти такой кейс
В итоге:
```
const user = await User.findById(id);
if (!user) {
   throw new Error('Not found')
}
req.user = user
next()
```
всего 6 строк

2021-11-28 17:51 UTC, merged